In [1]:
# Imports
import warnings
warnings.filterwarnings("ignore")

import pandas as pd
import numpy as np
from matplotlib import pyplot as plt
import seaborn as sns
import pycaret
np.random.seed(42) #seed global

pd.set_option("display.max_columns", None) #sem limite de colunas mostradas pelo pandas

In [2]:
df_og = pd.read_csv('../data/processed/dinn_scp_dataset.csv')
df = df_og.copy() #criando cópia do dataframe original
 
countries = ['Argentina','Colombia','Uruguay','Peru','Chile']
df = df.copy().query('country in @countries')
df.drop(['dmachexp', 'ict_mach_us_Y1','dict_mach','ict_mach_us_Y2'],axis=1,inplace=True,errors='ignore')
df.drop(['dinnpc','dinnpd','dongoingia', 'dabandia','fucode'],axis=1,inplace=True,errors='ignore')

In [3]:
isics = pd.read_csv('../data/raw/isics.csv')
isics_letras = isics.Code.str.isalpha()
isics = isics[~isics_letras]
isics = isics.loc[isics.Code.apply(len)<=3]
isics.Code = isics.Code.astype(int)
isics.Code = isics.Code.astype(str)
isics = isics.loc[isics.Code.apply(len)<=2]

df.isic3_2d = df.isic3_2d.astype('Int32')
df.isic3_2d = df.isic3_2d.astype('str')

df = df.merge(isics, left_on='isic3_2d',right_on='Code')
df.isic3_2d = df.Description
df.drop('Description',axis=1,inplace=True)

In [4]:
categs_setor_low = df.isic3_1d.value_counts(normalize=True)[df.isic3_1d.value_counts(normalize=True)<0.06].index
df['isic3_1d']=df['isic3_1d'].replace(categs_setor_low,'other')

In [5]:
total_null = df.isnull().sum().sort_values(ascending=False)
percent_null = (total_null/df.shape[0]).sort_values(ascending=False)
print(f'{total_null} \n\n{round(percent_null*100, 2)}')

target = 'dinn_scp'

#df_edit = df.drop(percent_null[percent_null>0.50].index,axis=1)
env_index = df[target].dropna().index
env_df = df.loc[env_index]

env_null = env_df.isnull().sum().sort_values(ascending=False)
percent_env_null = (env_null/env_df.shape[0]).sort_values(ascending=False)

df_env_edit = env_df.drop(percent_env_null[(percent_env_null>0.20) & (percent_env_null != target)].index,axis=1)
df_env_edit.info()

phd_Y3            108836
master_Y3         108836
undergrad_Y3      105184
nontert_Y3        105184
postgrad_Y3       105184
second_Y3         105175
export_us_Y3       94819
sales_us_Y3        84859
unidegree_Y3       84760
empl_Y3            84726
export_us_Y1       82603
sales_us_Y1        72643
degree_agrsc       68146
degree_nesc        63011
degree_et          63011
degree_hum         60055
degree_ssc         60055
degree_medsc       60055
degree_ingnesc     57971
export_us_Y2       44367
sales_us_Y2        34405
dexport            27784
master_Y2          25978
nontert_Y2         25978
postgrad_Y2        25978
phd_Y2             25978
undergrad_Y2       25978
master_Y1          25724
phd_Y1             25724
second_Y2          25193
undergrad_Y1       23585
postgrad_Y1        23585
nontert_Y1         23585
second_Y1          23049
dconexp            21648
isic3_1d           21161
IPexp_us_Y2        19116
IPexp_us_Y1        19116
unidegree_Y1       15219
unidegree_Y2       15127
dmktexp            15066
dIPexp             11291
dTTexp             10357
empl_Y2             8633
dictexp             7630
RD_empl             7234
empl_Y1             4976
dIDexp              1000
year                   0
isic3_2d               0
exp_f                  0
Code                   0
dinn_scp               0
drdintexp              0
drdextexp              0
dtrainexp              0
country                0
dtype: int64

phd_Y3            100.00
master_Y3         100.00
undergrad_Y3       96.64
nontert_Y3         96.64
postgrad_Y3        96.64
second_Y3          96.64
export_us_Y3       87.12
sales_us_Y3        77.97
unidegree_Y3       77.88
empl_Y3            77.85
export_us_Y1       75.90
sales_us_Y1        66.75
degree_agrsc       62.61
degree_et          57.90
degree_nesc        57.90
degree_hum         55.18
degree_ssc         55.18
degree_medsc       55.18
degree_ingnesc     53.26
export_us_Y2       40.77
sales_us_Y2        31.61
dexport            25.53
master_Y2          23.87
nontert_Y2         23.87
postgrad_Y2        23.87
phd_Y2             23.87
undergrad_Y2       23.87
master_Y1          23.64
phd_Y1             23.64
second_Y2          23.15
undergrad_Y1       21.67
postgrad_Y1        21.67
nontert_Y1         21.67
second_Y1          21.18
dconexp            19.89
isic3_1d           19.44
IPexp_us_Y2        17.56
IPexp_us_Y1        17.56
unidegree_Y1       13.98
unidegree_Y2       13.90
dmktexp            13.84
dIPexp             10.37
dTTexp              9.52
empl_Y2             7.93
dictexp             7.01
RD_empl             6.65
empl_Y1             4.57
dIDexp              0.92
Code                0.00
drdextexp           0.00
drdintexp           0.00
dinn_scp            0.00
dtrainexp           0.00
exp_f               0.00
isic3_2d            0.00
year                0.00
country             0.00
dtype: float64
<class 'pandas.core.frame.DataFrame'>
Int64Index: 108836 entries, 0 to 108835
Data columns (total 23 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   country       108836 non-null  object
 1   exp_f         108836 non-null  float64
 2   year          108836 non-null  int64
 3   isic3_1d      87675 non-null   object
 4   isic3_2d      108836 non-null  object
 5   empl_Y1       103860 non-null  float64
 6   empl_Y2       100203 non-null  float64
 7   unidegree_Y1  93617 non-null   float64
 8   unidegree_Y2  93709 non-null   float64
 9   RD_empl       101602 non-null  float64
 10  IPexp_us_Y1   89720 non-null   float64
 11  IPexp_us_Y2   89720 non-null   float64
 12  drdintexp     108836 non-null  int64
 13  drdextexp     108836 non-null  int64
 14  dictexp       101206 non-null  float64
 15  dTTexp        98479 non-null   float64
 16  dconexp       87188 non-null   float64
 17  dIPexp        97545 non-null   float64
 18  dtrainexp     108836 non-null  int64
 19  dIDexp        107836 non-null  float64
 20  dmktexp       93770 non-null   float64
 21  dinn_scp      108836 non-null  float64
 22  Code          108836 non-null  object
dtypes: float64(15), int64(4), object(4)
memory usage: 19.9+ MB

In [6]:
df.groupby(['country','isic3_1d']).count()#.value_counts(normalize=True)

                                      exp_f   year  isic3_2d  sales_us_Y1  \
country   isic3_1d
Argentina Manufacturing               10175  10175     10175         9962
Chile     Manufacturing                3541   3541      3541         3541
          other                        4089   4089      4089         4089
Colombia  Manufacturing               47947  47947     47947            0
          Wholesale and retail trade   9891   9891      9891            0
          other                        9698   9698      9698            0
Uruguay   Manufacturing                1334   1334      1334            0
          other                        1000   1000      1000            0

                                      sales_us_Y2  sales_us_Y3  export_us_Y1  \
country   isic3_1d
Argentina Manufacturing                      9962         9962             0
Chile     Manufacturing                      3541            0          3541
          other                              4089            0          4089
Colombia  Manufacturing                     25032            0             0
          Wholesale and retail trade         7563            0             0
          other                              7157            0             0
Uruguay   Manufacturing                         0         1334             0
          other                                 0         1000             0

                                      export_us_Y2  export_us_Y3  dexport  \
country   isic3_1d
Argentina Manufacturing                          0             0    10175
Chile     Manufacturing                       3541             0     3541
          other                               4089             0     4089
Colombia  Manufacturing                      25032             0    25032
          Wholesale and retail trade          7563             0     7563
          other                               7157             0     7157
Uruguay   Manufacturing                          0          1334     1334
          other                                  0          1000     1000

                                      empl_Y1  empl_Y2  empl_Y3  phd_Y1  \
country   isic3_1d
Argentina Manufacturing                 10096    10096    10096       0
Chile     Manufacturing                  3541     3541        0    2523
          other                          4089     4089        0    3877
Colombia  Manufacturing                 47945    47945        0   47760
          Wholesale and retail trade     9891     9891        0    9872
          other                          9698     9698        0    9610
Uruguay   Manufacturing                     0        0     1334       0
          other                             0        0     1000       0

                                      phd_Y2  phd_Y3  master_Y1  master_Y2  \
country   isic3_1d
Argentina Manufacturing                    0       0          0          0
Chile     Manufacturing                 2513       0       2523       2513
          other                         3862       0       3877       3862
Colombia  Manufacturing                47653       0      47760      47653
          Wholesale and retail trade    9843       0       9872       9843
          other                         9593       0       9610       9593
Uruguay   Manufacturing                    0       0          0          0
          other                            0       0          0          0

                                      master_Y3  postgrad_Y1  postgrad_Y2  \
country   isic3_1d
Argentina Manufacturing                       0            0            0
Chile     Manufacturing                       0         2523         2513
          other                               0         3877         3862
Colombia  Manufacturing                       0        47760        47653
          Wholesale and retail trade          0         9872         9843
          other                               0         9610         9593
Uruguay   Manufacturing                       0            0            0
          other                               0            0            0

                                      postgrad_Y3  undergrad_Y1  undergrad_Y2  \
country   isic3_1d
Argentina Manufacturing                         0             0             0
Chile     Manufacturing                         0          2523          2513
          other                                 0          3877          3862
Colombia  Manufacturing                         0         47760         47653
          Wholesale and retail trade            0          9872          9843
          other                                 0          9610          9593
Uruguay   Manufacturing                         0             0             0
          other                                 0             0             0

                                      undergrad_Y3  unidegree_Y1  \
country   isic3_1d
Argentina Manufacturing                          0          9974
Chile     Manufacturing                          0          2541
          other                                  0          4089
Colombia  Manufacturing                          0         47947
          Wholesale and retail trade             0          9891
          other                                  0          9698
Uruguay   Manufacturing                          0             0
          other                                  0             0

                                      unidegree_Y2  unidegree_Y3  degree_nesc  \
country   isic3_1d
Argentina Manufacturing                      10066         10089         5135
Chile     Manufacturing                       2541             0            0
          other                               4089             0            0
Colombia  Manufacturing                      47947             0        19313
          Wholesale and retail trade          9891             0         5811
          other                               9698             0         5386
Uruguay   Manufacturing                          0          1334         1011
          other                                  0          1000          744

                                      degree_et  degree_ingnesc  degree_ssc  \
country   isic3_1d
Argentina Manufacturing                    5135           10175        8091
Chile     Manufacturing                       0               0           0
          other                               0               0           0
Colombia  Manufacturing                   19313           19313       19313
          Wholesale and retail trade       5811            5811        5811
          other                            5386            5386        5386
Uruguay   Manufacturing                    1011            1011        1011
          other                             744             744         744

                                      degree_medsc  degree_agrsc  degree_hum  \
country   isic3_1d
Argentina Manufacturing                       8091             0        8091
Chile     Manufacturing                          0             0           0
          other                                  0             0           0
Colombia  Manufacturing                      19313         19313       19313
          Wholesale and retail trade          5811          5811        5811
          other                               5386          5386        5386
Uruguay   Manufacturing                       1011          1011        1011
          other                                744           744         744

                                      nontert_Y1  nontert_Y2  nontert_Y3  \
country   isic3_1d
Argentina Manufacturing                        0           0           0
Chile     Manufacturing                     2523        2513           0
          other                             3877        3862           0
Colombia  Manufacturing                    47760       47653           0
          Wholesale and retail trade        9872        9843           0
          other                             9610        9593           0
Uruguay   Manufacturing                        0           0           0
          other                                0           0           0

                                      second_Y1  second_Y2  second_Y3  \
country   isic3_1d
Argentina Manufacturing                       0          0          0
Chile     Manufacturing                    2541       2541          0
          other                            4089       4089          0
Colombia  Manufacturing                   47947      47947          0
          Wholesale and retail trade       9891       9891          0
          other                            9698       9698          0
Uruguay   Manufacturing                       0          0          0
          other                               0          0          0

                                      RD_empl  IPexp_us_Y1  IPexp_us_Y2  \
country   isic3_1d
Argentina Manufacturing                  5749        10175        10175
Chile     Manufacturing                  1816            0            0
          other                          3012            0            0
Colombia  Manufacturing                 47945        47947        47947
          Wholesale and retail trade     9891         9891         9891
          other                          9698         9698         9698
Uruguay   Manufacturing                  1334            0            0
          other                          1000            0            0

                                      drdintexp  drdextexp  dictexp  dTTexp  \
country   isic3_1d
Argentina Manufacturing                   10175      10175    10175   10175
Chile     Manufacturing                    3541       3541        0    3541
          other                            4089       4089        0    4089
Colombia  Manufacturing                   47947      47947    47947   47947
          Wholesale and retail trade       9891       9891     9891    9891
          other                            9698       9698     9698    9698
Uruguay   Manufacturing                    1334       1334     1334       0
          other                            1000       1000     1000       0

                                      dconexp  dIPexp  dtrainexp  dIDexp  \
country   isic3_1d
Argentina Manufacturing                 10175   10175      10175   10175
Chile     Manufacturing                     0       0       3541    2541
          other                             0       0       4089    4089
Colombia  Manufacturing                 47947   47947      47947   47947
          Wholesale and retail trade     9891    9891       9891    9891
          other                          9698    9698       9698    9698
Uruguay   Manufacturing                     0    1334       1334    1334
          other                             0    1000       1000    1000

                                      dmktexp  dinn_scp   Code
country   isic3_1d
Argentina Manufacturing                     0     10175  10175
Chile     Manufacturing                  3541      3541   3541
          other                          4089      4089   4089
Colombia  Manufacturing                 47947     47947  47947
          Wholesale and retail trade     9891      9891   9891
          other                          9698      9698   9698
Uruguay   Manufacturing                     0      1334   1334
          other                             0      1000   1000

In [7]:
df_env_edit.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 108836 entries, 0 to 108835
Data columns (total 23 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   country       108836 non-null  object
 1   exp_f         108836 non-null  float64
 2   year          108836 non-null  int64
 3   isic3_1d      87675 non-null   object
 4   isic3_2d      108836 non-null  object
 5   empl_Y1       103860 non-null  float64
 6   empl_Y2       100203 non-null  float64
 7   unidegree_Y1  93617 non-null   float64
 8   unidegree_Y2  93709 non-null   float64
 9   RD_empl       101602 non-null  float64
 10  IPexp_us_Y1   89720 non-null   float64
 11  IPexp_us_Y2   89720 non-null   float64
 12  drdintexp     108836 non-null  int64
 13  drdextexp     108836 non-null  int64
 14  dictexp       101206 non-null  float64
 15  dTTexp        98479 non-null   float64
 16  dconexp       87188 non-null   float64
 17  dIPexp        97545 non-null   float64
 18  dtrainexp     108836 non-null  int64
 19  dIDexp        107836 non-null  float64
 20  dmktexp       93770 non-null   float64
 21  dinn_scp      108836 non-null  float64
 22  Code          108836 non-null  object
dtypes: float64(15), int64(4), object(4)
memory usage: 19.9+ MB

In [8]:
from pycaret import classification as clf

exp_name = clf.setup(data = df_env_edit,  target = target,
                     remove_multicollinearity=True,
                     ignore_low_variance=True,
                     feature_selection=True,
                     fix_imbalance=True)

In [9]:
best_model = clf.compare_models(n_select=6)#include=['lightgbm','ridge','dt','ada',])#, exclude=['gbc'])

In [13]:
clf.tune_model(best_model[0])

LGBMClassifier(bagging_fraction=0.6, bagging_freq=1, boosting_type='gbdt',
               class_weight=None, colsample_bytree=1.0, feature_fraction=0.7,
               importance_type='split', learning_rate=0.5, max_depth=-1,
               min_child_samples=1, min_child_weight=0.001, min_split_gain=0.1,
               n_estimators=50, n_jobs=-1, num_leaves=90, objective=None,
               random_state=6951, reg_alpha=1, reg_lambda=0.001, silent='warn',
               subsample=1.0, subsample_for_bin=200000, subsample_freq=0)

In [14]:
clf.evaluate_model(best_model[0])

interactive(children=(ToggleButtons(description='Plot Type:', icons=('',), options=(('Hyperparameters', 'param…

In [16]:
original = clf.get_config('data_before_preprocess')
X_test = clf.get_config('X_test')
actual = clf.get_config('y_test')
preds = best_model[0].predict(X_test)

In [17]:
y_train = clf.get_config('y_train')

In [69]:
category = 'dtrainexp'
per_cat_results = pd.concat([original.loc[X_test.index,category].reset_index(drop=True),actual.reset_index(drop=True),pd.Series(preds)],axis=1,ignore_index=True,)
per_cat_results.columns = [category,'actual','predicted']

In [70]:
from sklearn.metrics import precision_score,recall_score,f1_score
results = []
index = per_cat_results[category].unique().tolist()
columns=['precision','recall','f-score']
for ctry in per_cat_results[category].unique():
    df_metrics = per_cat_results.query(f'{category} == @ctry')
    p = precision_score(df_metrics.actual,df_metrics.predicted)
    r = recall_score(df_metrics.actual,df_metrics.predicted)
    f = f1_score(df_metrics.actual,df_metrics.predicted)
    results.append([p,r,f])

metrics = pd.DataFrame(results,index=index,columns=columns)

In [71]:
df_env_edit.columns

Index(['country', 'exp_f', 'year', 'isic3_1d', 'isic3_2d', 'empl_Y1',
       'empl_Y2', 'unidegree_Y1', 'unidegree_Y2', 'RD_empl', 'IPexp_us_Y1',
       'IPexp_us_Y2', 'drdintexp', 'drdextexp', 'dictexp', 'dTTexp', 'dconexp',
       'dIPexp', 'dtrainexp', 'dIDexp', 'dmktexp', 'dinn_scp', 'Code'],
      dtype='object')

In [72]:
metrics.head(15)

   precision    recall   f-score
0   0.600482  0.369254  0.457300
1   0.604883  0.734997  0.663623

In [29]:
clf.get_config('prep_pipe')

Pipeline(memory=None,
         steps=[('dtypes',
                 DataTypes_Auto_infer(categorical_features=[],
                                      display_types=True, features_todrop=[],
                                      id_columns=[],
                                      ml_usecase='classification',
                                      numerical_features=[], target='dinn',
                                      time_features=[])),
                ('imputer',
                 Simple_Imputer(categorical_strategy='not_available',
                                fill_value_categorical=None,
                                fill_value_numerical=None,
                                numeric_strateg...
                 Advanced_Feature_Selection_Classic(ml_usecase='classification',
                                                    n_jobs=-1,
                                                    random_state=8191,
                                                    subclass='binary',
                                                    target='dinn',
                                                    top_features_to_pick=0.19999999999999996)),
                ('fix_multi',
                 Fix_multicollinearity(correlation_with_target_preference=None,
                                       correlation_with_target_threshold=0.0,
                                       target_variable='dinn', threshold=0.9)),
                ('dfs', 'passthrough'), ('pca', 'passthrough')],
         verbose=False)